### ISSUE TITLE
Showing appropriate wallpapers on workspaces in activities overview

### ISSUE THREAD

**Issue by ykhurshid** [blipk/Customised-Workspaces#13]
Not sure if I should call this a bug or a feature request but currently the wallpapers you see in the workspaces sidebar in the activities overview depends purely on which workspace you are currently on. 

It would be very nice if it showed the right wallpapers depending on the workspace though I imagine there are implementation complications that have prevented this from happening so far.

**Comment by blipk** [comment]
It's not really possible without rewriting the whole implementation thats already in gnome-shell.

This extension just changes the system default background to whichever value is saved for the active environment, and the workspace thumbnail on the sidebar is just a mirror of that workspace, which if its not active will be playing by the system wide default for whichever is.

I believe an earlier version of gnome-shell briefly had background managers for each workspaceThumbnail but it was buggy with this extension, part of the code is still in workspaceView.js

I don't really have the time to write a re-implementation of the ThumbnailsBox class, perhaps when I rewrite this extension with the next major version of gnome-shell.

If you would like to contribute you would have to update the injections in workspaceView to create a bgmanager for each Thumbnails box, then create a meta.window for that somehow display that instead of the background 'window' in this part of WorkspaceThumbnail:
```javascript
let windows = global.get_window_actors().filter(actor => {
            let win = actor.meta_window;
            return win.located_on_workspace(metaWorkspace);
        });
```

Links:
https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/master/js/ui/workspaceThumbnail.js
https://github.com/blipk/Customised-Workspaces/blob/master/worksets%40blipk.xyz/workspaceView.js

**Comment by blipk** [comment]
https://blogs.gnome.org/shell-dev/2021/03/12/gnome-40-your-extension/

`Backgrounds have moved into workspaces
This is a relatively minor change, but it affected two extensions I’m maintaining, so I decided it was worth mentioning after all.`

Looks like a promising change, but no details.
Look for the Gnome 40 release of this extension to have this feature implemented.

**Comment by blipk** [comment]
Hi @ykhurshid this has now been fixed.
