### ISSUE TITLE
error report

### ISSUE THREAD

**Issue by jhybe** [blipk/Customised-Workspaces#17]
hi,

following up from error report made through extensions.gnome.org. running ubuntu Ubuntu 20.04.2 LTS. gnome 3.36.8. not sure what other info you might need? 

repasting the error msg i got:
SyntaxError: expected expression, got '.'

Stack trace:
  @/home/XXX/.local/share/gnome-shell/extensions/worksets@blipk.xyz/prefs.js:33:17
  _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:204:33
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:132:13
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:175:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
  run@resource:///org/gnome/gjs/modules/script/package.js:222:19
  start@resource:///org/gnome/gjs/modules/script/package.js:206:5
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17

i don't usually use dash-to-dock as i find it doesn't work with customised-workspaces, and i need customised-workspaces more. but now that i installed the most recent update and this extension broke, i enabled dash-to-dock again. 

thanks!

**Comment by blipk** [comment]
Hi @jhybe 

As I thought it's likely due to Ubuntu using a rather outdated version of GJS which doesn't support certain operators.
I've reverted the changes for now, can you test the changes I've made in the github repo (can use the zip package) and let me know if that works? Before I push the changes to the extension website.


Could you also let me know what the problem with dash-to-dock is? Last I checked (admittedly some time ago) it was working fine with this extension alongside.

**Comment by THgithub19** [comment]
After update from the working version 27 to version 29 of this extension I get exactly the same error message reported by jhybe. This is on Ubuntu 20.04 LTS with Gnome 3.36.8
By reverting to v27 my workspace configuration is restored.

**Comment by THgithub19** [comment]
I tested the changes in the github repo using the zip package, that works for me.
Cheers.

**Comment by blipk** [comment]
Thanks @THgithub19 there is now a version 30 with those changes on the gnome extensions website so that should work.
